name: bup # you probably want to 'snapcraft register <name>'
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Bup backup # 79 char long summary
description: |
  Backs things up

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
base: core20

apps:
  bup:
    command: usr/local/bin/bup

parts:
  bup:
    source: .
    plugin: autotools
    build-environment:
     - PYTHON: '/usr/bin/python3'
     - DIST_PYTHON: |-
             \"\${SNAP}\"/usr/bin/python3
     - DIST_PATH: |-
             \${SNAP}/usr/local/sbin:\${SNAP}/usr/local/bin:\${SNAP}/usr/sbin:\${SNAP}/usr/bin:\${SNAP}/sbin:\${SNAP}/bin
    build-packages: 
     - python3
     - build-essential
     - git
     - libacl1-dev
     - python3-dev
     - python3-fuse
     - python3-pyxattr
     - libreadline-dev
     - acl 
     - attr
     - python3-tornado
    stage-packages: 
     - python3
     - python3-fuse
     - python3-pyxattr
     - python3-tornado
     - libpython3-stdlib
     - libpython3.8-stdlib
     - libpython3.8-minimal
     - git
     - python3-pip
     - python3-setuptools
     - python3-wheel
     - python3-venv
     - python3-minimal
     - python3-distutils
     - python3-pkg-resources
     - python3.8-minimal
     - libacl1
     - acl
     - attr
     - par2
